# don't change this
configversion: 3

#DataBase
DataBase:
  # You need to choose if you will use SQLite or Mysql ( default is SQLite )
  Type: SQLite
#MySQL config if you will use mysql ( set type to mysql )
MySQL:
  Host: localhost
  Username: root
  Password: change_this
  Port: '3306'
  Database: minecraft
# Pool Size ( For Mysql Connection )
ConnectionPoolSize : 10

# how many days after delete old records
PurgeOldRecords: 3d
# You can disable auto purge and do it on command
AutoPurge : true
# How many seconds for run purge 
# 43200 = 12h ( 12h in 12h )
# Only if AutoPurge is true
PurgeOldRecordsTaskTimer: 43200

# This Option will keep all protection blocks on memory
# ( increase use of memory ) and will search against 
# memory not database every time need it
SearchAgainstMemory: false

# Save to Database in Queue Not will save direct 
# will put on queue list and will save 1 each time
# this can save you server from having too much 
# inserting on database at same time
SaveQueue : false

# Run task on each seconds for SaveQueue
RunTaskSeconds : 2

# Enable update
UpdaterNotify: true

# Allow Protected Blocks place inside protected area
AllowProtectedBlockInsideArea: false

#Defaults Area Flags
# if allow all player to move inside area of others players
AllowMoveInside: true

# The ID of the wand (Stick = 280, Wooden axe = 271)
WandID: 280

# The ID of the info wand (Stick = 280, Wooden axe = 271)
InfoWandID: 271

# Protected Block - Blocks only owner can destroy ( and admin bypass )
Protected:
- '1'
- '4'
- '5'
- '17'
- '20'
- '23'
- '24'
- '25'
- '26'
- '29'
- '33'
- '35'
- '41'
- '42'
- '43'
- '44'
- '45'
- '47'
- '48'
- '49'
- '53'
- '58'
- '61'
- '63'
- '65'
- '67'
- '68'
- '69'
- '77'
- '79'
- '84'
- '85'
- '86'
- '89'
- '91'
- '95'
- '96'
- '98'
- '101'
- '102'
- '108'
- '109'
- '110'
- '112'
- '116'
- '117'
- '121'
- '123'
- '124'
- '125'
- '126'
- '128'
- '131'
- '132'
- '134'
- '135'
- '136'
- '138'
- '139'
- '140'
- '143'
- '145'
- '146'
- '147'
- '148'
- '151'
- '155'
- '154'
- '158'
- '159'
- '160'
- '171'
- '170'
- '172'
- '323'
- '380'
- '389'
- '390'